/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Bebidas;
import Clases.Menu;
import Util.AdminSerializacion;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Cleymer
 */
public class frmBebidas extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form frmBebidas
     */
     private boolean _agregando;
     private int _indice=-1;
    public frmBebidas() {
        initComponents();
        this.setTitle("Gestion Bebidas");
        
        try {
            ActualizarElementosTabla();
        } catch (Exception e) {
            System.out.println("Error al actualizar los elementos " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroupDescripcion = new javax.swing.ButtonGroup();
        rbGroupTamaño = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbnDescripcion1 = new javax.swing.JRadioButton();
        rbnDescripcion = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtBebidas = new javax.swing.JTable();
        rbnTamanio = new javax.swing.JRadioButton();
        rbnTamanio1 = new javax.swing.JRadioButton();
        rbnTamanio2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 45, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 42, 53, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 77, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 74, 173, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tamaño");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 106, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Descripcion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 137, -1, -1));

        rbGroupDescripcion.add(rbnDescripcion1);
        rbnDescripcion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbnDescripcion1.setText("Helada");
        rbnDescripcion1.setEnabled(false);
        getContentPane().add(rbnDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 133, -1, -1));

        rbGroupDescripcion.add(rbnDescripcion);
        rbnDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbnDescripcion.setText("Caliente");
        rbnDescripcion.setEnabled(false);
        rbnDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(rbnDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 133, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 166, 69, -1));

        txtPrecio.setEditable(false);
        txtPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 163, 110, -1));

        jtBebidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtBebidasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtBebidas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 583, 146));

        rbGroupTamaño.add(rbnTamanio);
        rbnTamanio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbnTamanio.setText("Grande");
        rbnTamanio.setEnabled(false);
        rbnTamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnTamanioActionPerformed(evt);
            }
        });
        getContentPane().add(rbnTamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 102, -1, -1));

        rbGroupTamaño.add(rbnTamanio1);
        rbnTamanio1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbnTamanio1.setText("Mediano");
        rbnTamanio1.setEnabled(false);
        rbnTamanio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnTamanio1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbnTamanio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 102, -1, -1));

        rbGroupTamaño.add(rbnTamanio2);
        rbnTamanio2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbnTamanio2.setText("Pequeño");
        rbnTamanio2.setEnabled(false);
        getContentPane().add(rbnTamanio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 102, -1, -1));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editaar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_guardar.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 1.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnReporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        jLabel7.setText("Nuevo");

        jLabel8.setText("Editar");

        jLabel9.setText("Guardar");

        jLabel10.setText("Buscar");

        jLabel11.setText("Eliminar");

        jLabel12.setText("Salir");

        jLabel13.setText("Reporte");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(38, 38, 38)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel13)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)))
                .addGap(55, 55, 55))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 460, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2020-08-14 at 8.46.18 PM.jpeg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void rbnDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnDescripcionActionPerformed

    private void rbnTamanio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnTamanio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnTamanio1ActionPerformed

    private void rbnTamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnTamanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnTamanioActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this._agregando = true;
        estadoControles(true);
        estadoBotones(false);
        
        this.txtCodigo.setText("");
        this.txtNombre.setText("");
        this.txtPrecio.setText("");
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this._agregando=false;
        estadoControles(true);
            estadoBotones(false);
            this.txtCodigo.setEditable(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        /**
             * PASOS
             * 1. Solicitar los valores al usuario
             * 2. Crear la instancia
             * 3. Setear los valores de la instancia
             * 4. Agregar la instancia Bebida a la gestion
             * 5. Mostrar los valores
             */
            //Paso 1,2,3 Son pasos comunes para agregar y modificar
            //Paso 1
            String  _nombre, _tamanio="ND", _descripcion="ND";
            
            int _codigo=Integer.parseInt(txtCodigo.getText());
            _nombre=this.txtNombre.getText();
            double _precio=Double.parseDouble(txtPrecio.getText());
            
            
             if(this.rbnDescripcion1.isSelected()){
            _descripcion="Helada";
            }else{
                if(this.rbnDescripcion.isSelected()){
                _descripcion="Caliente";
                }
            }
             
             if(this.rbnTamanio.isSelected()){
            _tamanio="Grande";
            }else{
                if(this.rbnTamanio1.isSelected()){
                _tamanio="Mediano";
                }else{
                if(this.rbnTamanio2.isSelected()){
                  _tamanio="Pequeño";  
                }
                }  
            }
            //Paso 2 
        Bebidas bebida=new Bebidas();
         try{   
            //Paso 3
        bebida.set_codigo(_codigo);
        bebida.set_nombre(_nombre);
        bebida.set_tamanio(_tamanio);
        bebida.set_descripcion(_descripcion);
        bebida.set_precio(_precio);
       
        
        
        if(this._agregando){//Nuevo Bebida
            
            //Paso 4
            MDIPrincipal.gBebidas.Agregar(bebida);
            
        }else{ //Esta editando las bebidas
            MDIPrincipal.gBebidas.Modificar(bebida, this._indice);
        }
        //Paso 5
            ActualizarElementosTabla();
            estadoControles(false);
            estadoBotones(true);
            
            //Paso 6 Serializar Informacion
            AdminSerializacion.serializacion(MDIPrincipal.gBebidas, "gBebidas.obj");
         }catch(Exception e) {
             JOptionPane.showMessageDialog(this, "Ha ocurrido un error " + e.getMessage());
         } 
    }                                          
    
    public void ActualizarElementosTabla(){
        String [] titulos={"Codigo", "Nombre", "Tamaño", "Descripcion", "Precio"};
        DefaultTableModel dt=new DefaultTableModel(MDIPrincipal.gBebidas.getArrayGestion(), titulos);
        this.jtBebidas.setModel(dt);
    }
         public void estadoControles(boolean _estado){
         this.txtCodigo.setEditable(_estado);
         this.txtNombre.setEditable(_estado);
         this.txtPrecio.setEditable(_estado);
         this.rbnTamanio.setEnabled(_estado);
         this.rbnTamanio1.setEnabled(_estado);
         this.rbnTamanio2.setEnabled(_estado);
         this.rbnDescripcion.setEnabled(_estado);
         this.rbnDescripcion1.setEnabled(_estado);
         
         
     }
         
         public void estadoBotones(boolean _estado){
             this.btnBuscar.setEnabled(_estado);
             this.btnNuevo.setEnabled(_estado);
             this.btnEditar.setEnabled(_estado);
             this.btnEliminar.setEnabled(_estado);
             this.btnGuardar.setEnabled(!_estado);
        
    
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtBebidasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtBebidasMousePressed
        // TODO add your handling code here:
        _indice=this.jtBebidas.getSelectedRow();
        if(_indice!=-1){
        Bebidas _bebidas=MDIPrincipal.gBebidas.getBebidasByIndex(_indice);
        mostrarElemento(_bebidas);
        }
        
    }//GEN-LAST:event_jtBebidasMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(_indice>=0){
        int resultado=JOptionPane.showConfirmDialog(null,"¿Esta Seguro?","Warning", JOptionPane.YES_NO_OPTION);
        if(resultado==JOptionPane.YES_OPTION){
            MDIPrincipal.gBebidas.eliminarporIndice(_indice);
            ActualizarElementosTabla();
        }
        }else{
            JOptionPane.showMessageDialog(this,"Favor Seleccione el elemento de la tabla que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String _codigo= JOptionPane.showInputDialog("Ingrese el codigo de bebida");
        Bebidas _bebidaEncontrada=MDIPrincipal.gBebidas.Buscar(Integer.parseInt(_codigo));
        if(_bebidaEncontrada==null){
        JOptionPane.showMessageDialog(this, "Bebida no Encontrada");
        }else{
        mostrarElemento(_bebidaEncontrada);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        String nombreArchivo = "Bebidas";
        String contenido = MDIPrincipal.gBebidas.getInformacionGestion();
        String ruta = "Reportes\\" + nombreArchivo;

        try {
            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte generado correctamente");
        } catch (Exception e) {
            System.out.println("error" + e);
        }
    }//GEN-LAST:event_btnReporteActionPerformed
public void mostrarElemento(Bebidas _bebidas){
    this.txtCodigo.setText(Integer.toString(_bebidas.get_codigo()));
    this.txtNombre.setText(_bebidas.get_nombre());
    this.txtPrecio.setText(Double.toString(_bebidas.get_precio()));
    this.rbnDescripcion.setText(_bebidas.get_descripcion());
    this.rbnTamanio.setText(_bebidas.get_tamanio());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtBebidas;
    private javax.swing.ButtonGroup rbGroupDescripcion;
    private javax.swing.ButtonGroup rbGroupTamaño;
    private javax.swing.JRadioButton rbnDescripcion;
    private javax.swing.JRadioButton rbnDescripcion1;
    private javax.swing.JRadioButton rbnTamanio;
    private javax.swing.JRadioButton rbnTamanio1;
    private javax.swing.JRadioButton rbnTamanio2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
