/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Clases.Forma_De_Pago;
import Util.AdminSerializacion;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cleymer
 */
public class frmFormaDePago extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmFormaDePago
     */
    private boolean _agregando;
    private int _indiceSeleccion=-1;
    public frmFormaDePago() {
        initComponents();
        this.setTitle("Gestion de Forma de Pago");
        
        try {
            ActualizarElementosTabla();
        } catch (Exception e) {
            System.out.println("Error al actualizar los elementos " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbFormadePago = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbnDescripcion = new javax.swing.JRadioButton();
        rbnDescripcion1 = new javax.swing.JRadioButton();
        rbnDescripcion2 = new javax.swing.JRadioButton();
        btnNuevo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFormaDePago = new javax.swing.JTable();
        btnReporte = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 36, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 33, 168, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Descripcion Metodo de pago");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 81, -1, -1));

        rbFormadePago.add(rbnDescripcion);
        rbnDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbnDescripcion.setText("Tarjeta de Credito");
        rbnDescripcion.setEnabled(false);
        getContentPane().add(rbnDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 77, -1, -1));

        rbFormadePago.add(rbnDescripcion1);
        rbnDescripcion1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbnDescripcion1.setText("Tarjeta de Debito");
        rbnDescripcion1.setEnabled(false);
        getContentPane().add(rbnDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 103, -1, -1));

        rbFormadePago.add(rbnDescripcion2);
        rbnDescripcion2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbnDescripcion2.setText("Efectivo");
        rbnDescripcion2.setEnabled(false);
        getContentPane().add(rbnDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 129, 109, -1));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 60, 60));

        jLabel3.setText("Nuevo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editaar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 60, 60));

        jLabel4.setText("Editar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 50, 60));

        jLabel5.setText("Eliminar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_guardar.png"))); // NOI18N
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 50, 60));

        jLabel6.setText("Guardar");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 1.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 60, 60));

        jLabel7.setText("Buscar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel8.setText("Salir");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 60, 60));

        jLabel9.setText("Reporte");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        jtFormaDePago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtFormaDePago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtFormaDePagoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtFormaDePago);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 161));

        btnReporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 60, 60));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2020-08-14 at 8.46.18 PM.jpeg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -8, 570, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this._agregando=true;
          estadoControles(true);
        estadoBotones(false);
        this.txtCodigo.setText("");
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this._agregando=false;
         estadoControles(true);
        estadoBotones(false);
         this.txtCodigo.setEditable(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        /**
             * PASOS
             * 1. Solicitar los valores al usuario
             * 2. Crear la instancia
             * 3. Setear los valores de la instancia
             * 4. Agregar la instancia Forma de Pago a la gestion
             * 5. Mostrar los valores
             */
            
            //Paso 1
           
         int _codigo=Integer.parseInt(txtCodigo.getText());
         String _descripcion="ND";
         
             if(this.rbnDescripcion.isSelected()){
            _descripcion="Tarjeta de Credito";
            }else{
                if(this.rbnDescripcion1.isSelected()){
                _descripcion="Tarjeta de Debito";
                }else{
                if(this.rbnDescripcion2.isSelected()){
                  _descripcion="Efectivo";  
                }
                }  
            }
            
            //Paso 2 
        Forma_De_Pago formapago=new Forma_De_Pago();
            try{
            //Paso 3
           formapago.set_codigo(_codigo);
           formapago.set_descripcion(_descripcion);
          
           
        if(this._agregando){//Nueva Forma de Pago
            
            //Paso 4
            MDIPrincipal.gForma_De_Pago.Agregar(formapago);
            
            
        }else{ //Esta editando las formas de pago
            MDIPrincipal.gForma_De_Pago.Modificar(formapago, this._indiceSeleccion);
        }
        //Paso 5
            ActualizarElementosTabla();
            estadoControles(false);
            estadoBotones(true);
            
            //Paso 6 Serializar Informacion
            AdminSerializacion.serializacion(MDIPrincipal.gForma_De_Pago, "gFormaDePago.obj");
         }catch(Exception e) {
             JOptionPane.showMessageDialog(this, "Ha ocurrido un error " + e.getMessage());
         }
    }                                          

    public void ActualizarElementosTabla(){
        String [] titulos={"Codigo", "Metodo"};
        DefaultTableModel dt=new DefaultTableModel(MDIPrincipal.gForma_De_Pago.getArrayGestion(), titulos);
        this.jtFormaDePago.setModel(dt);
    }
           public void estadoControles(boolean _estado){
         this.txtCodigo.setEditable(_estado);
         this.rbnDescripcion2.setEnabled(_estado);
         this.rbnDescripcion.setEnabled(_estado);
         this.rbnDescripcion1.setEnabled(_estado);
         
         
     }
         
         public void estadoBotones(boolean _estado){
             this.btnBuscar.setEnabled(_estado);
             this.btnNuevo.setEnabled(_estado);
             this.btnEditar.setEnabled(_estado);
             this.btnEliminar.setEnabled(_estado);
             this.btnGuardar.setEnabled(!_estado);
    
                                
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtFormaDePagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFormaDePagoMousePressed
        // TODO add your handling code here:
         _indiceSeleccion=this.jtFormaDePago.getSelectedRow();
        if(_indiceSeleccion!=-1){
        Forma_De_Pago _formapago=MDIPrincipal.gForma_De_Pago.getFormaPagoByIndex(_indiceSeleccion);
        mostrarElemento(_formapago);
        }
    }//GEN-LAST:event_jtFormaDePagoMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(_indiceSeleccion>=0){
        int resultado=JOptionPane.showConfirmDialog(null,"¿Esta Seguro?","Warning", JOptionPane.YES_NO_OPTION);
        if(resultado==JOptionPane.YES_OPTION){
            MDIPrincipal.gForma_De_Pago.eliminarporIndice(_indiceSeleccion);
            ActualizarElementosTabla();
        }
        }else{
            JOptionPane.showMessageDialog(this,"Favor Seleccione el elemento de la tabla que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
         String _codigo= JOptionPane.showInputDialog("Ingrese el codigo de la forma de pago");
        Forma_De_Pago _formaEncontrada=MDIPrincipal.gForma_De_Pago.Buscar(Integer.parseInt(_codigo));
        if(_formaEncontrada==null){
        JOptionPane.showMessageDialog(this, "Forma de Pago no Encontrado");
        }else{
        mostrarElemento(_formaEncontrada);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
         String nombreArchivo = "Forma de Pago";
        String contenido = MDIPrincipal.gForma_De_Pago.getInformacionGestion();
        String ruta = "Reportes\\" + nombreArchivo;

        try {
            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte generado correctamente");
        } catch (Exception e) {
            System.out.println("error" + e);
        }
    }//GEN-LAST:event_btnReporteActionPerformed
public void mostrarElemento(Forma_De_Pago _formapago){
    
      //this.txtCodigo.setText(_formapago.get_codigo());
      this.rbnDescripcion.setText(_formapago.get_metodo());
      
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtFormaDePago;
    private javax.swing.JLabel lblfondo;
    private javax.swing.ButtonGroup rbFormadePago;
    private javax.swing.JRadioButton rbnDescripcion;
    private javax.swing.JRadioButton rbnDescripcion1;
    private javax.swing.JRadioButton rbnDescripcion2;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
