/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.Cliente;
import java.util.Date;
import Clases.ReservacionMesas;
import Util.AdminFechas;
import Util.AdminSerializacion;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cleymer
 */
public class frmReservacionMesas extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmReservacionMesas
     */
    private boolean _agregando;
    
    private int _indiceSeleccion=-1;
    private Cliente _clienteReservacion;
    public frmReservacionMesas() {
        initComponents();
        this.setTitle("Gestion Reservacion de Mesas");
        
        try {
            ActualizarElementosTabla();
        } catch (Exception e) {
            System.out.println("Error al actualizar los elementos " + e.getMessage());
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroupTamanio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbntamanio = new javax.swing.JRadioButton();
        rbntamanio3 = new javax.swing.JRadioButton();
        rbntamanio2 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtReservacionMesas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        btnCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboDia = new javax.swing.JComboBox<>();
        cboMes = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblmes = new javax.swing.JLabel();
        lbldia = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblfondo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tamaño");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 83, 70, -1));

        rbGroupTamanio.add(rbntamanio);
        rbntamanio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbntamanio.setText("Individual");
        rbntamanio.setEnabled(false);
        rbntamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbntamanioActionPerformed(evt);
            }
        });
        getContentPane().add(rbntamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 79, -1, -1));

        rbGroupTamanio.add(rbntamanio3);
        rbntamanio3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbntamanio3.setText("Familiar");
        rbntamanio3.setEnabled(false);
        getContentPane().add(rbntamanio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 137, 85, -1));

        rbGroupTamanio.add(rbntamanio2);
        rbntamanio2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbntamanio2.setText("Pareja");
        rbntamanio2.setEnabled(false);
        getContentPane().add(rbntamanio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 111, 85, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jtReservacionMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtReservacionMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtReservacionMesasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtReservacionMesas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 118, 470, 170));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Descripcion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 323, 79, -1));

        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(new java.awt.Color(204, 204, 204));
        txtDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 323, 156, 51));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Hora");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 277, 51, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editaar.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/delete.png"))); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_guardar.png"))); // NOI18N
        btnGuardar.setActionCommand("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton buscar 1.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/boton_salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnReporte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonReportes 1.png"))); // NOI18N
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        jLabel7.setText("Nuevo");

        jLabel8.setText("Editar");

        jLabel9.setText("Eliminar");

        jLabel10.setText("Guardar");

        jLabel11.setText("Buscar");

        jLabel12.setText("Salir");

        jLabel13.setText("Reporte");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, 80));

        txtHora.setEditable(false);
        txtHora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 274, 66, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cliente");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 38, 46, -1));

        lblCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 38, 231, 14));

        btnCliente.setText("...");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 38, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fecha:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 222, 51, -1));

        cboDia.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(cboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 219, -1, -1));

        cboMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre", " " }));
        getContentPane().add(cboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 219, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("Año");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 195, 41, -1));

        lblmes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblmes.setText("Mes");
        getContentPane().add(lblmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 195, 46, -1));

        lbldia.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbldia.setText("Dia");
        getContentPane().add(lbldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 195, 35, -1));

        txtAnio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 219, 70, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2020-08-14 at 8.46.18 PM.jpeg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -3, 890, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbntamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbntamanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbntamanioActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        this._agregando=true;
        estadoControles(true);
            estadoBotones(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this._agregando=false;
        estadoControles(true);
            estadoBotones(false);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //Paso 1
        String _tamanio="ND", _descripcion, _hora;
	 Date _fecha;
        
        _hora=this.txtHora.getText();
        _descripcion=this.txtDescripcion.getText();
         
        if(this.rbntamanio.isSelected()){
            _tamanio="Individual";
            }else{
                if(this.rbntamanio2.isSelected()){
                _tamanio="Pareja";
                }else{
                if(this.rbntamanio3.isSelected()){
                  _tamanio="Familiar";  
                }
                }  
            }
        String dia, mes, anio;
                dia = Integer.toString(this.cboDia.getSelectedIndex());
                mes = Integer.toString(this.cboMes.getSelectedIndex());
                anio = this.txtAnio.getText();

                _fecha = AdminFechas.stringToDate(dia + "-" + mes + "-" + anio);
        //Paso 2
        ReservacionMesas reservacion=new ReservacionMesas();
        
        try{   
    //Paso 3
            reservacion.set_fecha(_fecha);
            reservacion.set_tamanio(_tamanio);
            reservacion.setHora(_hora);
            reservacion.set_descripcion(_descripcion);
            reservacion.set_cliente(_clienteReservacion);
        
        if(this._agregando){
        
        //Paso 4
        MDIPrincipal.gReservacion.Agregar(reservacion);
        
       
        }else{
            MDIPrincipal.gReservacion.Modificar(reservacion, this._indiceSeleccion);
        
        }
        //Paso5
       ActualizarElementosTabla();
            estadoControles(false);
            estadoBotones(true);
            
            //Paso 6 Serializar Informacion
            AdminSerializacion.serializacion(MDIPrincipal.gReservacion, "gReservacion.obj");
         }catch(Exception e) {
             JOptionPane.showMessageDialog(this, "Ha ocurrido un error " + e.getMessage());
         }
        
    }
    public void ActualizarElementosTabla(){
        String[] titulos={"Cliente" , "Tamanio", "Fecha", "Hora","Descripcion"};
        DefaultTableModel dt=new DefaultTableModel(MDIPrincipal.gReservacion.getArrayGestion(),titulos);
        this.jtReservacionMesas.setModel(dt);
    }
      public void estadoControles(boolean _estado){
         this.rbntamanio.setEnabled(_estado);
         this.rbntamanio2.setEnabled(_estado);
         this.rbntamanio3.setEnabled(_estado);
         this.txtHora.setEditable(_estado);
         this.txtDescripcion.setEditable(_estado);
        
         
     }
         public void estadoBotones(boolean _estado){
             this.btnBuscar.setEnabled(_estado);
             this.btnNuevo.setEnabled(_estado);
             this.btnEditar.setEnabled(_estado);
             this.btnEliminar.setEnabled(_estado);
             this.btnGuardar.setEnabled(!_estado);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jtReservacionMesasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtReservacionMesasMousePressed
        // TODO add your handling code here:
         _indiceSeleccion=this.jtReservacionMesas.getSelectedRow();
        if(_indiceSeleccion!=-1){
        ReservacionMesas _reservacion=MDIPrincipal.gReservacion.getReservacionByIndex(_indiceSeleccion);
        mostrarElemento(_reservacion);
        
        }
    }//GEN-LAST:event_jtReservacionMesasMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(_indiceSeleccion>=0){
        int resultado=JOptionPane.showConfirmDialog(null,"¿Esta Seguro?","Warning", JOptionPane.YES_NO_OPTION);
        if(resultado==JOptionPane.YES_OPTION){
            MDIPrincipal.gReservacion.eliminarporIndice(_indiceSeleccion);
            ActualizarElementosTabla();
        }
        }else{
            JOptionPane.showMessageDialog(this,"Favor Seleccione el elemento de la tabla que desea eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String _codigo= JOptionPane.showInputDialog("Ingrese el codigo de la Reservacion");
        ReservacionMesas _reservacionEncontrada=MDIPrincipal.gReservacion.Buscar(_codigo);
        if(_reservacionEncontrada==null){
        JOptionPane.showMessageDialog(this, "Reservacion no Encontrado");
        }else{
        mostrarElemento(_reservacionEncontrada);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        String _codigoCliente=JOptionPane.showInputDialog(this, "Código del cliente");
        
        _clienteReservacion=MDIPrincipal.gCliente.obtenerCliente(Integer.parseInt(_codigoCliente));
        
        if(_clienteReservacion==null){
            JOptionPane.showMessageDialog(this,"No se encuentra ese cliente"+ _codigoCliente);
        }else{
            this.lblCliente.setText(_clienteReservacion.get_nombres()+" "+_clienteReservacion.get_apellidos());
        }
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
         String nombreArchivo = "Reservacion de Mesas";
        String contenido = MDIPrincipal.gReservacion.getInformacionGestion();
        String ruta = "Reportes\\" + nombreArchivo;

        try {
            FileOutputStream archivo = new FileOutputStream(ruta + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(contenido));
            doc.close();
            JOptionPane.showMessageDialog(null, "Reporte generado correctamente");
        } catch (Exception e) {
            System.out.println("error" + e);
        }
    }//GEN-LAST:event_btnReporteActionPerformed
    public void mostrarElemento(ReservacionMesas _reservacion){
        
    this.txtDescripcion.setText(_reservacion.get_descripcion());
    this.rbntamanio.setText(_reservacion.get_tamanio());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboDia;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtReservacionMesas;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lbldia;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JLabel lblmes;
    private javax.swing.ButtonGroup rbGroupTamanio;
    private javax.swing.JRadioButton rbntamanio;
    private javax.swing.JRadioButton rbntamanio2;
    private javax.swing.JRadioButton rbntamanio3;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtHora;
    // End of variables declaration//GEN-END:variables
}
